services:
    xgc0gk0socw4cgs8k88gkg84-063211107377:
        image: 'xgc0gk0socw4cgs8k88gkg84:1ba086d8e33efb8e6e9eeeb6d0c1df6dfbb2be39'
        container_name: xgc0gk0socw4cgs8k88gkg84-063211107377
        restart: unless-stopped
        expose:
            - '3000'
        networks:
            coolify:
                aliases:
                    - xgc0gk0socw4cgs8k88gkg84-063211107377
        mem_limit: '0'
        memswap_limit: '0'
        mem_swappiness: 60
        mem_reservation: '0'
        cpus: 0.0
        cpu_shares: 1024
        env_file:
            - .env
        labels:
            - traefik.enable=true
            - traefik.http.middlewares.gzip.compress=true
            - traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https
            - traefik.http.routers.http-0-xgc0gk0socw4cgs8k88gkg84.entryPoints=http
            - traefik.http.routers.http-0-xgc0gk0socw4cgs8k88gkg84.middlewares=redirect-to-https
            - 'traefik.http.routers.http-0-xgc0gk0socw4cgs8k88gkg84.rule=Host(`eric-test2.co`) && PathPrefix(`/`)'
            - traefik.http.routers.http-0-xgc0gk0socw4cgs8k88gkg84.service=http-0-xgc0gk0socw4cgs8k88gkg84
            - traefik.http.routers.https-0-xgc0gk0socw4cgs8k88gkg84.entryPoints=https
            - traefik.http.routers.https-0-xgc0gk0socw4cgs8k88gkg84.middlewares=gzip
            - 'traefik.http.routers.https-0-xgc0gk0socw4cgs8k88gkg84.rule=Host(`eric-test2.co`) && PathPrefix(`/`)'
            - traefik.http.routers.https-0-xgc0gk0socw4cgs8k88gkg84.service=https-0-xgc0gk0socw4cgs8k88gkg84
            - traefik.http.routers.https-0-xgc0gk0socw4cgs8k88gkg84.tls.certresolver=letsencrypt
            - traefik.http.routers.https-0-xgc0gk0socw4cgs8k88gkg84.tls=true
            - traefik.http.services.http-0-xgc0gk0socw4cgs8k88gkg84.loadbalancer.server.port=3000
            - traefik.http.services.https-0-xgc0gk0socw4cgs8k88gkg84.loadbalancer.server.port=3000
            - 'caddy_0.encode=zstd gzip'
            - 'caddy_0.handle_path.0_reverse_proxy={{upstreams 3000}}'
            - 'caddy_0.handle_path=/*'
            - caddy_0.header=-Server
            - 'caddy_0.try_files={path} /index.html /index.php'
            - 'caddy_0=https://eric-test2.co'
            - caddy_ingress_network=coolify
            - coolify.managed=true
            - coolify.version=4.0.0-beta.441
            - coolify.applicationId=1
            - coolify.type=application
            - coolify.name=xgc0gk0socw4cgs8k88gkg84
            - coolify.resourceName=erics-website
            - coolify.projectName=erics-website
            - coolify.serviceName=erics-website
            - coolify.environmentName=production
            - coolify.pullRequestId=0
networks:
    coolify:
        external: true
        name: coolify
        attachable: true
